.\" (C) Copyright 2023 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH KQSNAKE 1 "October 03 2023" "Проект Kqsnake" "Игра Змейка"
.SH НАЗВАНИЕ
kqsnake \- Еще одна игра Змейка
.SH СИНТАКСИС
.B kqsnake
.RI [ параметры ]
.SH ОПИСАНИЕ
.B kqsnake
Ещё одна реализация игры "Змейка"
.PP
.SH ПАРАМЕТРЫ
Программа соблюдает обычный для GNU команд синтаксис, включая параметры с двумя дефисами (`-').
Краткий список параметров предоставлен ниже.
.TP
.B \-h, \-H, \-\-help
Показать список параметров.
.TP
.B \-v, \-\-version
Показать текущую версию программмы.
