.\" (C) Copyright 2023 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH KQSNAKE 1 "October 03 2023" "Project Kqsnake" "Schlangespiel"
.SH NAME
kqsnake \- Die andere Lebenspielrealisation
.SH ÜBERSICHT
.B kqsnake
.RI [ Argumente ]
.SH BESCHREIBUNG
.B kqsnake
Jezt die andere Schlangespiel
.PP
.SH ARGUMENTE
Dieses Programm folgt der üblichen GNU-Befehlszeilensyntax mit langen
Argumenten, die mit zwei Bindestrichen (`-') anfangen.
Eine Argumentenzusammenfassung finden Sie unten.
.TP
.B \-h, \-H, \-\-help
Argumentenzusammenfassung einzeigen
.TP
.B \-v, \-\-version
App Version einzeigen
