.\" (C) Copyright 2023 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH KQSNAKE 1 "October 03 2023" "KQSNAKE project" "Snake Game"
.SH NAME
kqsnake \- Game Of Life
.SH SYNOPSIS
.B kqsnake
.RI [ options ]
.SH DESCRIPTION
.B kqsnake
Another Snake Game realization
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-H, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
