name: kqsnake # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0-3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Another Snake Game under Qt # 79 char long summary
description: |
  Another Snake Game realization Collect as many apples as you can.

website: https://www.darkguard.net
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: [amd64]
  - build-on: [arm64]
apps:
  kqsnake:
    common-id: org.kde.kqsnake.desktop
    command: usr/bin/kqsnake
    desktop: org.kde.kqsnake.desktop
    extensions:
      - kde-neon
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy


parts:
  org-desk:
    after: [my-part]
    plugin: dump
    source: desktop/
    override-stage: |
      craftctl default

      # Point icon to the correct location
      sed -i -e 's|Icon=kqsnake|Icon=kqsnake.png|g' $CRAFT_STAGE/org.kde.kqsnake.desktop
    organize:
      64x64/kqsnake.png: kqsnake.png
    stage: [kqsnake.png, org.kde.kqsnake.desktop]
  my-part:
    build-attributes:
      - enable-patchelf
    # See 'snapcraft plugins'
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DKDE_INSTALL_USE_QT_SYS_PATHS=false
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"

    source: .
    build-packages:
      - gcc
      - cmake
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libkf5configwidgets-dev
      - libkf5xmlgui-dev
      - libkf5crash-dev
      - libkf5doctools-dev
      - libkf5i18n-dev
      - extra-cmake-modules
      - qtchooser
      - libx11-dev

